'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {LocalL2Manager}=require('../local-l2');
const {BurstPreparationQueue,burstPreparationReadiness}=require('../burst-preparation');
const {BurstScalpManager}=require('../burst-scalp');
function snap(){return {available:true,ageMs:100,spreadBps:1,localL2:{available:true,sequenceHealthy:true,confidence:.9},orderFlow:{windows:{'1s':{buyRatio:.85,sellRatio:.15,priceMoveBps:6,buyQuote:9000,sellQuote:1000},'3s':{buyRatio:.85,sellRatio:.15,priceMoveBps:12,trades:8,buyQuote:18000,sellQuote:2000},'5s':{buyRatio:.85,sellRatio:.15}}},level1Ofi:{windows:{'1s':{normalizedOfi:.8,queueImbalanceCurrent:.7,micropriceBps:1},'3s':{normalizedOfi:.8,transitions:4}}}};}
test('R39 burst allocation enters full recent analysis cache and preserves the six-symbol cap',()=>{let now=100000;const m=new LocalL2Manager({now:()=>now});for(const s of ['A','B','C','D','E','F'])m.ensureSymbol(s+'USDT');assert.equal(m.ensureSymbol('GUSDT'),null);assert.ok(m.ensureSymbol('GUSDT',{priority:'BURST'}));assert.equal(m.states.size,6);assert.equal(m.ensureSymbol('HUSDT',{priority:'BURST'}),null);now+=30001;assert.ok(m.ensureSymbol('HUSDT',{priority:'BURST'}));assert.ok(m.state('GUSDT'));});
test('R39 position priority preempts burst reservation but burst cannot evict positions',()=>{const m=new LocalL2Manager({now:()=>100000,maxSymbols:2});m.setPositionSymbols(['COREUSDT']);m.ensureSymbol('COREUSDT');m.ensureSymbol('BURSTUSDT',{priority:'BURST'});assert.equal(m.ensureSymbol('OTHERUSDT',{priority:'BURST'}),null);m.setPositionSymbols(['COREUSDT','NEWCOREUSDT']);m.ensureSymbol('NEWCOREUSDT');assert.ok(m.state('COREUSDT'));assert.ok(m.state('NEWCOREUSDT'));assert.equal(m.state('BURSTUSDT'),null);assert.equal(m.states.size,2);});
test('R39 burst reservation expires and normal analysis can reclaim a sufficiently old slot',()=>{let now=100000;const m=new LocalL2Manager({now:()=>now,maxSymbols:1});m.ensureSymbol('AUSDT',{priority:'BURST',leaseMs:1000});assert.equal(m.ensureSymbol('BUSDT'),null);now+=61000;assert.equal(m.isReserved('AUSDT'),false);assert.ok(m.ensureSymbol('BUSDT'));});
test('R39 preparation survives rotating radar lists, is bounded, and turns over after timeout',()=>{let now=0;const events=[],q=new BurstPreparationQueue({now:()=>now,onExpire:(...x)=>events.push(x)}),pool=['A','B','C','D'].map(s=>({symbol:s+'USDT'}));assert.deepEqual(q.pick(pool).map(x=>x.symbol),['AUSDT','BUSDT']);now+=20000;assert.deepEqual(q.pick(pool.slice(2)).map(x=>x.symbol),['AUSDT','BUSDT']);now+=120000;const next=q.pick(pool);assert.equal(next.length,2);assert.ok(next.every(x=>!['AUSDT','BUSDT'].includes(x.symbol)));assert.equal(events.length,2);});
test('R39 readiness checks data availability without forcing a direction or trigger score',()=>{const s=snap();s.orderFlow.windows['3s'].buyRatio=.1;s.level1Ofi.windows['3s'].normalizedOfi=-.8;delete s.orderFlow.windows['1s'];assert.equal(burstPreparationReadiness(s).ready,true);{const x=snap();x.level1Ofi.windows['3s'].normalizedOfi=null;const r=burstPreparationReadiness(x);assert.equal(r.ready,true,'R46: missing OFI is neutral');assert.equal(r.ofiAvailable,false);}for(const mutate of [s=>s.ageMs=2501,s=>s.localL2.sequenceHealthy=false,s=>s.orderFlow.windows['3s'].trades=0]){const x=snap();mutate(x);assert.equal(burstPreparationReadiness(x).ready,false);}});
test('R39 missing 1s trigger cannot be hidden by strong remaining evidence',()=>{const s=snap(),m=new BurstScalpManager({marketStream:{snapshot:()=>s},now:()=>1000});m.arm({symbol:'ABCUSDT',side:'LONG',triggerThreshold:.82,preMove:{state:'IGNITION',direction:'LONG'}});assert.equal(m.evaluateArmed('ABCUSDT').trigger,true);s.orderFlow.windows['1s'].priceMoveBps=null;const e=m.evaluateArmed('ABCUSDT');assert.equal(e.trigger,false);assert.ok(e.evidence.contradictions.includes('TRIGGER_WINDOW_INCOMPLETE'));});
test('R39 authorization expiry emits persistent-observer event and cannot trigger after TTL',()=>{let now=1000;const events=[],m=new BurstScalpManager({marketStream:{snapshot:snap},now:()=>now,onEvent:x=>events.push(x)});m.arm({symbol:'ABCUSDT',side:'LONG',ttlMs:30000});now+=30001;assert.notEqual(m.evaluateArmed('ABCUSDT').reason,'NOT_ARMED','R46: TTL floor 120 s');now+=90000;assert.equal(m.evaluateArmed('ABCUSDT').reason,'NOT_ARMED');assert.ok(events.some(x=>x.kind==='DISARM'&&x.reason==='TTL_EXPIRED'));});
function controllerFixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'r39-burst-'));fs.mkdirSync(path.join(root,'config'));fs.writeFileSync(path.join(root,'config','live-policy.json'),JSON.stringify({armMinutes:1440,expectedLeverage:5,maxEntryDeviationPct:1,limits:{maxRiskPctPerTrade:1,maxNotionalPctPerTrade:20,maxDailyLossPct:100,maxOpenPositions:3,maxFamilyExposurePct:40},apiPermissions:{configured:true,futuresEnabled:true,withdrawalsEnabled:false,ipRestricted:true}}));fs.writeFileSync(path.join(root,'config','leader-auto.json'),JSON.stringify({enabled:true,marginQuote:30,leverage:10,maxOpenPositions:1,allowLong:true,allowShort:true,burstLiveEnabled:true}));const state={now:1000000,ready:false,capacity:true,calls:0},events=[],s=snap();const stream={ensureSymbol(){},ensureLocalL2:()=>state.capacity?{}:null,snapshot:()=>state.ready?s:{available:false,localL2:{available:false,state:'COLD'}},localL2:{releaseReservation(){}}};const pool=['A','B','C','D'].map(x=>({symbol:x+'USDT',direction:'LONG',state:'IGNITION',preMove:{state:'IGNITION',direction:'LONG'}}));const controller=require('../live-controller').createLiveController({root,clock:()=>state.now,store:{journal:(k,s,p)=>events.push({k,s,p})},scanner:{scan:async()=>({preMoveSignals:pool,nearExplosion:pool})},pipeline:{},committee:async()=>({}),market:{marketStream:stream,cachedChartContext:symbol=>({available:true,symbol,packet:{},asOf:state.now,ageMs:0})},burstJudge:async()=>{state.calls++;return {ok:true,called:true,decision:'ARM_LONG',side:'LONG',ttlMs:30000,reason:'EARLY_EXPANSION',triggerThreshold:.82};},fetchImpl:async()=>{throw Error('NO_NETWORK_IN_FIXTURE');}});return {controller,state,events,root};}
test('R39 controller waits for the same warming candidates, then asks JEV and arms without exchange writes',async()=>{const f=controllerFixture();let r=await f.controller.burstArmTick();assert.equal(r.checked,2);assert.equal(f.state.calls,0);assert.ok(r.results.every(x=>x.reason==='BURST_STREAM_NOT_FRESH'));f.state.now+=20000;f.state.ready=true;r=await f.controller.burstArmTick();assert.equal(f.state.calls,2);assert.equal(r.results.filter(x=>x.armed).length,2);assert.equal(f.controller.status().armed,false);assert.ok(f.events.some(x=>x.k==='BURST_PREAUTH_REVIEW'&&x.p.requestReadiness.ready));assert.equal(f.controller.burstStatus().preparation.length,0);});
test('R39 controller exposes L2 capacity wait without wasting a JEV call',async()=>{const f=controllerFixture();f.state.capacity=false;const r=await f.controller.burstArmTick();assert.equal(f.state.calls,0);assert.ok(r.results.every(x=>x.reason==='BURST_L2_CAPACITY_WAIT'));assert.ok(f.events.some(x=>x.k==='BURST_PREPARATION'));});
test('R39 user disabling OTO revokes pending burst authorization without an exchange write',async()=>{const f=controllerFixture();f.state.ready=true;await f.controller.burstArmTick();assert.equal(f.controller.burstStatus().armed.length,2);const cfg=path.join(f.root,'config','leader-auto.json'),data=JSON.parse(fs.readFileSync(cfg));data.enabled=false;fs.writeFileSync(cfg,JSON.stringify(data));const r=await f.controller.burstScalpTick();assert.equal(r.reason,'LEADER_AUTO_DISABLED');assert.equal(f.controller.burstStatus().armed.length,0);assert.ok(f.events.some(x=>x.k==='BURST_WATCH_EVENT'&&x.p.kind==='DISARM'&&x.p.reason==='LEADER_AUTO_DISABLED'));});
