'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const J=require('../jev-decision');

function plan(id,side,lane,n){
  return {id,side,lane,entryPrice:100+n,stopPrice:98+n,takeProfit1:102+n,takeProfit2:104+n,takeProfit3:108+n,invalidationPrice:97.8+n,invalidationSource:'CONFIRMED_SWING',originTF:lane==='5M_SCALP'?'5m':'15m',ownerTF:lane==='5M_SCALP'?'5m':'15m',basis:'STRUCTURE_LOCATION',stopPct:1.9,stopAtr:1.1,geometryNote:'Executable geometry remains canonical and must not be inferred from compressed prose. '+('G'.repeat(210)),formingOwnerTF:{direction:'BEAR',changeAtr:-0.42,againstSide:side==='LONG'},extraNarrative:'N'.repeat(420)};
}

function pass2Questions(plans){
  const criteria={WAIT:'No supplied executable plan is worth taking now. WAIT is a valid strategic decision and should be chosen when the opportunity is not real enough right now.'};
  for(const p of plans)criteria[p.id]=[p.side,p.lane,'entry='+p.entryPrice,'stop='+p.stopPrice,'tp1='+p.takeProfit1,'tp2='+p.takeProfit2,'tp3='+p.takeProfit3,'invalidation='+p.invalidationPrice,'invalidationSource='+p.invalidationSource,'frame='+p.originTF,'basis='+p.basis,'stopDistance='+p.stopPct+'% ('+p.stopAtr+'x '+p.originTF+' ATR)','geometry='+p.geometryNote,'forming '+p.originTF+' candle (not closed) '+p.formingOwnerTF.direction+' '+p.formingOwnerTF.changeAtr+' ATR'].join(' | ');
  return {
    trade_plan:{type:'choice',instructions:'Choose the single best action now. Select one supplied executable plan only when direction, lane, timing, location and risk geometry are justified by the complete core market packet plus requested evidence; otherwise choose WAIT.',criteria},
    setup_family:{type:'choice',instructions:'Classify the actual setup family for measured learning. Do not use a generic lane label.',criteria:{TREND_PULLBACK:'Trend continuation after a controlled pullback.',BREAKOUT_RETEST:'Breakout with acceptance/retest and remaining path.',SWEEP_RECLAIM:'Liquidity sweep followed by reclaim/acceptance.',FAILED_BREAKOUT:'Failed breakout/trap reversal.',RANGE_FADE:'Range extreme rejection toward equilibrium/opposite boundary.',MOMENTUM_CONTINUATION:'Immediate continuation with enough room and execution quality.',MEAN_REVERSION:'Exhaustion/stretched location reverting toward a credible mean.',SQUEEZE_CROWDING:'Squeeze/crowding setup supported by derivatives/liquidity.',STRUCTURAL_REVERSAL:'Structure transition/reversal with coherent invalidation.',NONE_WAIT:'No trade setup is strong enough now; use with WAIT.'}},
    entry_timing:{type:'choice',instructions:'Decide whether this is actually an entry NOW. If direction may be right but location/timing is not, choose a WAIT_* timing.',criteria:{MARKET_NOW:'Current price is a justified entry location now.',WAIT_PULLBACK:'Wait for a better pullback into structure/OB/FVG/OTE location.',WAIT_BREAKOUT_RETEST:'Wait for breakout acceptance and/or retest.',WAIT_SWEEP_RECLAIM:'Wait for the relevant liquidity sweep and reclaim/rejection.',WAIT_STRUCTURE_CLOSE:'Wait for a confirming closed-candle structure event.',WAIT_NEW_EVIDENCE:'Wait for materially changed evidence.'}},
    wait_reason:{type:'choice',instructions:'Explain why entry is not MARKET_NOW. This is diagnostic discipline, not an extra veto. Choose NONE_MARKET_NOW only when a concrete plan is selected and current entry is justified. Any WAIT_* timing must have one specific reason rather than generic uncertainty.',criteria:{NONE_MARKET_NOW:'Current location and execution quality justify entry now.',LOCATION_POOR:'Direction/setup may be valid but current price is a poor location or too extended.',STRUCTURE_UNCONFIRMED:'A specific closed-candle structure event is still materially required.',BREAKOUT_RETEST_REQUIRED:'Breakout acceptance/retest is materially required before entry.',SWEEP_RECLAIM_REQUIRED:'A specific liquidity sweep/reclaim or rejection is materially required.',EDGE_INSUFFICIENT:'Available evidence does not provide enough edge right now.',ADVERSE_SELECTION_RISK:'The setup direction may remain valid, but current public order-flow/depth behavior makes immediate entry vulnerable to being trapped; wait for flow normalization/new evidence.',DATA_QUALITY:'Material market/execution data is stale, missing, or unreliable.',KNOWLEDGE_GAP:'A material concept is not understood well enough to act without verified research.'}},
    edge_basis:{type:'choice',instructions:'Identify the primary evidence family carrying the edge. Diagnostic/learning context only.',criteria:{STRUCTURE_LOCATION:'Structure plus location/dealing range.',LIQUIDITY_SMC:'Sweep/reclaim, FVG, OB, OTE/Fib or liquidity geometry.',ORDER_FLOW_DEPTH:'Order-flow/CVD/depth/microstructure.',DERIVATIVES_POSITIONING:'OI/funding/taker/positioning/liquidations.',PATTERN_PRICE_ACTION:'Classical/candlestick pattern plus price action.',COMBINATION:'Coherent combination; no single family dominates.',NO_EDGE:'No robust edge.'}},
    pre_entry_flow_assessment:{type:'choice',instructions:'Read coreMarketPacket.microstructure.preEntryAdverseSelection for the selected direction. This is diagnostic telemetry for JEV entry timing, not a hard gate and not a probability. If data is warming/sparse choose DATA_INSUFFICIENT. If immediate public flow/depth is materially adverse to entry now choose TRAP_RISK_WAIT even when the higher-level setup remains valid.',criteria:{SUPPORTS_PLAN:'Pre-entry microstructure materially supports immediate execution for the selected side.',NEUTRAL_OR_MIXED:'Pre-entry flow is usable but not directionally decisive.',TRAP_RISK_WAIT:'The directional thesis may remain valid, but immediate adverse-selection/trap evidence makes MARKET_NOW inferior.',DATA_INSUFFICIENT:'The pre-entry layer is warming, sparse, stale or otherwise not reliable enough to influence timing.'}},
    management_style:{type:'choice',instructions:'If a trade plan is selected, choose how JEV wants the position managed after entry. If WAIT is selected this answer is recorded but not executed.',criteria:{TP1_BE_TRAIL:'Take a first partial at TP1, protect around breakeven when appropriate, then trail the runner as structure evolves.',STRUCTURE_TRAIL:'Manage primarily by evolving 5m/15m structure; keep the runner until the thesis is structurally broken.',PARTIALS_RUNNER:'Use staged partial profits while preserving a runner until thesis failure.',HOLD_TO_INVALIDATION:'Avoid premature exits; hold unless the JEV thesis/invalidation breaks or a later JEV review changes the plan.'}},
    target_profile:{type:'choice',instructions:'Choose the reward geometry that best fits this specific opportunity. This is a JEV strategic choice, not a fixed score or timeframe rule.',criteria:{FAST_SCALP:'Prioritize earlier profit realization: approximately 0.75R / 1.5R / 2.5R.',BALANCED:'Balanced geometry: approximately 1R / 2R / 3R.',RUNNER_EXTENDED:'Preserve more convexity: approximately 1R / 2R / 4R.',DEFENSIVE:'Use closer targets when continuation room is limited: approximately 0.75R / 1.25R / 2R.'}},
    partial_profile:{type:'choice',instructions:'Choose how much of the position should remain for later targets/runner. JEV owns this strategic distribution.',criteria:{THIRDS:'Roughly one third at each stage; final third is the runner portion.',HALF_QUARTER_RUNNER:'Take about half early, one quarter later, keep one quarter as runner.',RUNNER_HEAVY:'Take about one quarter at TP1, one quarter at TP2, keep about half for TP3/runner.'}},
    breakeven_rule:{type:'choice',instructions:'Choose when protective management may move toward breakeven. This does not permit widening risk.',criteria:{AFTER_TP1:'Breakeven protection may be considered after TP1 is achieved.',AFTER_1R_CLOSE:'Breakeven protection may be considered after a closed-candle move of about 1R.',STRUCTURE_ONLY:'Do not force breakeven mechanically; protect only when structure/evidence supports it.'}},
    trail_rule:{type:'choice',instructions:'Choose the preferred runner trailing evidence. Later JEV position review remains authoritative.',criteria:{'5M_STRUCTURE':'Trail primarily from evolving closed 5m swing/structure evidence.','15M_STRUCTURE':'Give the runner more room and trail primarily from closed 15m structure.','JEV_DYNAMIC':'Let later JEV position reviews choose the appropriate structure/timeframe dynamically.'}}
  };
}

function memory(){
  const analog=(i,win)=>({eventId:'p2-'+i,symbol:'TESTUSDT',side:i%2?'LONG':'SHORT',family:'SWEEP_RECLAIM',lane:i%2?'5M_SCALP':'15M_TRADE',netPnl:win?5.2:-4.1,rMultiple:win?1.1:-0.8,exitType:win?'TP1_TRAIL':'STOP',similarity:.74,fidelity:'IMMUTABLE_R2544_21',quality:'FULL',actionHint:'FLOW_MIXED',lesson:(win?'winner ':'loser ')+('measured detailed lesson '.repeat(48))});
  return {alwaysOn:true,source:'MEASURED',measuredSampleCount:177,jevLessonCount:24,lifetime:{samples:177,netPnl:-170.9},tradeLessons:{version:'R2544.21',samples:177,lifetime:{samples:177,net:-170.9},worked:['worked '+('W'.repeat(600)),'worked2 '+('W'.repeat(500))],failed:['failed '+('F'.repeat(600)),'failed2 '+('F'.repeat(500))],repeatedMistakes:['RAPID_REENTRY_AFTER_LOSS '+('M'.repeat(320)),'LEADER_CHASE_LONG '+('M'.repeat(300)),'WIDE_STOP '+('M'.repeat(250))],current:{tier:'TOP4_10',LONG:[4,50,-2],SHORT:[3,33,-4]},symbol:{samples:4,recent:['a','b','c']},byPreEntryFlow:Array.from({length:8},(_,i)=>['STATE'+i+'|LONG',10+i,45+i,-5+i,.8,2.1,-2.4])},caseMemory:{version:'R2544.21',available:true,samples:8,summary:{netPnl:-1.2,avgR:-.1},fidelity:{immutable:8},counterexamples:{winnerCount:4,loserCount:4},analogs:[analog(1,true),analog(2,false),analog(3,true)]},caseMemoryByLane:{LONG_5M_SCALP:{available:true,samples:4,summary:{netPnl:1},fidelity:{immutable:4},counterexamples:{winnerCount:2,loserCount:2},analogs:[analog(4,true),analog(5,false)]},SHORT_15M_TRADE:{available:true,samples:4,summary:{netPnl:-1},fidelity:{immutable:4},counterexamples:{winnerCount:2,loserCount:2},analogs:[analog(6,false),analog(7,true)]}}};
}

function body(){
  const plans=[plan('LONG_5M_SCALP','LONG','5M_SCALP',0),plan('SHORT_5M_SCALP','SHORT','5M_SCALP',1),plan('LONG_15M_TRADE','LONG','15M_TRADE',2),plan('SHORT_15M_TRADE','SHORT','15M_TRADE',3)];
  const core={contract:'R2537_JEV_CONTEXT_COMPLETE_READ_ONLY',symbol:'TESTUSDT',livePrice:102,coreFrames:{'5m':{available:true,fresh:true,close:102,trend:'UP',rsi14:62,atrPct:1.2,recentFairValueGaps:[{side:'BULL',low:100,high:101}],orderBlocks:{bullish:[{low:99,high:100}]},fibLevels:{retracement:{'0.618':100.2}},oteReference:{longDiscountZone:{low:99.5,high:100.5}}},'15m':{available:true,fresh:true,close:102,trend:'UP',rsi14:69,atrPct:1.8,recentFairValueGaps:[{side:'BULL',low:99,high:100}],orderBlocks:{bearish:[{low:103,high:104}]},fibLevels:{retracement:{'0.618':99.8}},oteReference:{shortPremiumZone:{low:103,high:104}}}},timingFrames:{'1m':{available:true,fresh:true,close:102,trend:'UP',preMove:{state:'WATCH'}},'3m':{available:true,fresh:true,close:102,trend:'UP',preMove:{state:'WATCH'}}},higherContext:{'30m':{available:true,fresh:true,close:101,trend:'UP'},'45m':{available:true,fresh:true,close:101,trend:'UP',synthetic:true},'1h':{available:true,fresh:true,close:100,trend:'UP'},'4h':{available:true,fresh:true,close:98,trend:'UP'},'1d':{available:true,fresh:true,close:92,trend:'UP'}},levelMap:{above:[{price:103.2}],below:[{price:100.2}]},liquidationHistory:{available:true,zones:[]},microstructure:{preEntryAdverseSelection:{version:'R2544.21',authority:'EVIDENCE_ONLY_JEV_FINAL',reliability:{quality:'HIGH',score:1,usable:true},samplingConfidence:{shortWindow:{score:.67,quality:'MODERATE'},overall:{score:.86,quality:'FULL',usable:true},sparseWindows:['OFI_5s_UNAVAILABLE']},localL2:{available:true,state:'HEALTHY',sequenceHealthy:true,ageMs:80,resyncCount5m:0,confidence:.91,confidenceQuality:'HIGH',multiLevelOfi:.34,depthImbalance:.21,wallPersistence:{side:'BID',score:.62},liquidityPull:{side:'NONE'},replenishment:{side:'BID',score:.55},absorption:{side:'BID',confidence:.58},authority:'EVIDENCE_ONLY',canVeto:false},actionHint:'FLOW_MIXED'},livePublicPacket:'X'.repeat(29000)},derivatives:{available:true,openInterest:{delta5mPct:.1},fundingRate:.00001,modeledLiquidation:{available:true,authority:'SHADOW_EVIDENCE_ONLY',observed:false,estimated:true,events:7,baselineHours:60,density:{longBelow:.64,shortAbove:.38},canVeto:false,executionAuthority:false}},observedLiquidations:{available:true,count:2},dataQuality:{advisoryUsable:true},global:{riskState:'NORMAL'}};
  const evidence={requested:['ORDER_FLOW_CVD','DEPTH','DERIVATIVES','LIQUIDATIONS'],timing1m:{summary:'T'.repeat(480),patterns:Array.from({length:6},(_,i)=>({id:i,note:'p'.repeat(120)}))},timing3m:{summary:'T'.repeat(420)},higherTf:{'1h':{summary:'H'.repeat(300)},'4h':{summary:'H'.repeat(300)},'1d':{summary:'H'.repeat(300)}},orderFlow:{available:true,summary:'O'.repeat(520)},depth:{available:true,summary:'D'.repeat(420)},derivatives:{available:true,summary:'R'.repeat(420)},observedLiquidations:{available:true,count:22,summary:'L'.repeat(300)},historyOutcome:{recentOutcomes:Array.from({length:7},(_,i)=>({id:i,note:'history '.repeat(35)})),stats:Array.from({length:7},(_,i)=>({id:i,note:'stat '.repeat(30)}))},visual:{authority:'EVIDENCE_ONLY',requestedFrames:['5m','15m'],attached:2,required:2,source:'LOCAL',text:'visual '.repeat(350),frames:{raw:'Z'.repeat(1600)}}};
  return {model:'typesafe/jev-1.13',state:{description:'JEV PASS-2 final strategic choice. '+('D'.repeat(850)),decisionContract:{version:'R2544.25',authority:'JEV_FINAL',phase:'PASS2_FINAL',lanes:{'5M_SCALP':'x'.repeat(130),'15M_TRADE':'y'.repeat(130)},rules:['NO_MANDATORY_CHECKLIST','NO_FIXED_SCORE','NO_2_OF_3','NO_HARD_15M_VETO','NUMERIC_TRUTH_OVER_VISUAL','OPTIONAL_MISSING_NOT_NEGATIVE'],microstructure:'M'.repeat(280),memory:'E'.repeat(220),knowledge:'K'.repeat(160)},professionalTraderCortex:{version:'R2.5.3.4',mode:'LIVE_REASONING_REFERENCE_READ_ONLY',reference:'## Decision doctrine\n'+('Cortex '.repeat(390))},dynamicKnowledge:{entries:[{topic:'microstructure',family:'MICROSTRUCTURE',verifiedAt:'2026-09-30',summary:'K'.repeat(500),keyPoints:['a'.repeat(180),'b'.repeat(180)],sourceUrls:['https://example.com']}]},experienceMemory:memory(),pass1Handoff:{laneFocus:'15M_TRADE',directionFocus:'LONG',requestedEvidence:['ORDER_FLOW_CVD','DEPTH'],knowledgeResearchRequested:false,knowledgeFamily:null,snapshotHash:'abc'},coreMarketPacket:core,record:{attention:{contract:'R2.5.3.2_JEV_SOVEREIGN_5M_15M',authority:{decisionOwner:'JEV',scanner:'ATTENTION_ONLY',workers:'EVIDENCE_ONLY'},symbol:'TESTUSDT',radar:{sideHint:'LONG',source:'GAINER_APPROACH',targetSources:['A','B','C'],attackRank:7,projectedRank:4,rankVelocity:3.2,rankAcceleration:1.1,m1:.4,m3:.8,m5:1.2,volumeAcceleration:2.1,rangeExpansion:1.4,spreadBps:2.2,oiDeltaPct:.1,takerBuyRatio:.61,fundingRate:.00001,ladder:{rank:7,prevRank:14,velocity5m:7,tier:'4-10'}},livePrice:102,baseFrames:{'5m':{available:true,fresh:true,close:102,trend:'UP'},'15m':{available:true,fresh:true,close:102,trend:'UP'}},dataQuality:{advisoryUsable:true},semantics:{scannerSideIsHintOnly:true,noPreJevQualification:true,noScoreThresholds:true,noTwoOfThreeRequirement:true,noHard15mStrategicVeto:true,formingCandleIsContextOnly:true,numericTruth:'BINANCE_BRAINHUB',visualWorker:'AUDIT_ON_DEMAND_EVIDENCE_ONLY'}},requestedEvidence:evidence,executablePlanOptions:plans}},questions:pass2Questions(plans)};
}

test('R2544.25 residual PASS-2 question schema preserves IDs/choice keys while removing repeated plan prose',()=>{
  const q=body().questions;const base=J.compactPass2Questions(q);const tight=J.compactPass2QuestionsResidual(base);
  assert.deepEqual(Object.keys(tight),Object.keys(q));
  for(const id of Object.keys(q))assert.deepEqual(Object.keys(tight[id].criteria),Object.keys(q[id].criteria),id);
  assert.deepEqual(Object.keys(tight.trade_plan.criteria),Object.keys(q.trade_plan.criteria));
  assert.match(tight.trade_plan.criteria.LONG_5M_SCALP,/Canonical geometry/);
  assert.ok(Buffer.byteLength(JSON.stringify(tight),'utf8')<Buffer.byteLength(JSON.stringify(base),'utf8'));
  assert.ok(Buffer.byteLength(JSON.stringify(tight),'utf8')<=4300);
});

test('R2544.25 residual PASS-2 record keeps executable price geometry and requested evidence identities',()=>{
  const raw=body().state.record;const base=J.compactPass2Record(raw);const tight=J.compactPass2RecordResidual(base);
  assert.deepEqual(tight.executablePlanOptions.map(x=>x.id),raw.executablePlanOptions.map(x=>x.id));
  for(let i=0;i<tight.executablePlanOptions.length;i++)for(const k of ['side','lane','entryPrice','stopPrice','takeProfit1','takeProfit2','takeProfit3','invalidationPrice','invalidationSource','originTF'])assert.equal(tight.executablePlanOptions[i][k],raw.executablePlanOptions[i][k],k);
  assert.deepEqual(tight.requestedEvidence.requested,raw.requestedEvidence.requested);
  assert.equal(tight.attention.symbol,'TESTUSDT');assert.equal(tight.attention.baseFramesDetail,'SEE_CORE_MARKET_PACKET');
  assert.ok(Buffer.byteLength(JSON.stringify(tight),'utf8')<=3500);
});

test('R2544.25 residual PASS-2 memory preserves measured aggregate and winner/loser counterexamples',()=>{
  const tight=J.compactMemoryForPass2Residual(J.compactMemoryForPass2Final(memory()));
  assert.equal(tight.measuredSampleCount,177);assert.equal(tight.lifetime.samples,177);
  assert.equal(tight.caseMemory.counterexamples.winnerCount,4);assert.equal(tight.caseMemory.counterexamples.loserCount,4);
  assert.ok(tight.caseMemory.analogs.some(x=>Number(x.netPnl)>0));assert.ok(tight.caseMemory.analogs.some(x=>Number(x.netPnl)<0));
  assert.ok(Buffer.byteLength(JSON.stringify(tight),'utf8')<=3200);
});

test('R2544.25 live-worst-class core near 31k is dynamically residual-budgeted under 46k without changing protected truth',()=>{
  const input=body();const before=J.protectedCoreTruth(input);const out=J.prepareDecisionRequest(input);
  assert.ok(out.diagnostics.beforeBytes>75000,`fixture before=${out.diagnostics.beforeBytes}`);
  assert.ok(out.diagnostics.contextBudget.coreMarketPacketBytes>=30000,`core=${out.diagnostics.contextBudget.coreMarketPacketBytes}`);
  assert.equal(out.diagnostics.pass,2);assert.equal(out.ok,true,JSON.stringify(out.diagnostics));assert.ok(out.diagnostics.bytes<=46000,`bytes=${out.diagnostics.bytes}`);
  assert.equal(out.diagnostics.blockReason,null);assert.equal(out.diagnostics.coreTruthProtected,true);assert.deepEqual(J.protectedCoreTruth(out.body),before);
  assert.equal(out.diagnostics.contextBudget.residualBudgetApplied,true);assert.ok(out.diagnostics.contextBudget.hardHeadroomBytes>=2000,`headroom=${out.diagnostics.contextBudget.hardHeadroomBytes}`);
  assert.ok(out.diagnostics.trimStepsApplied.includes('PASS2_RESIDUAL_QUESTION_TIGHT'));assert.ok(out.diagnostics.trimStepsApplied.includes('PASS2_RESIDUAL_RECORD_TIGHT'));
});

test('R2544.25 stress core above observed live worst still reaches target or fails closed without touching core',()=>{
  const input=body();input.state.coreMarketPacket.microstructure.livePublicPacket='X'.repeat(31000);const before=J.protectedCoreTruth(input);const out=J.prepareDecisionRequest(input);
  assert.equal(out.ok,true,JSON.stringify(out.diagnostics));assert.ok(out.diagnostics.bytes<=46000,`bytes=${out.diagnostics.bytes}`);assert.equal(out.diagnostics.coreTruthProtected,true);assert.deepEqual(J.protectedCoreTruth(out.body),before);
  assert.ok(out.diagnostics.trimStepsApplied.includes('PASS2_RESIDUAL_MEMORY_TIGHT'));assert.ok(out.diagnostics.contextBudget.hardHeadroomBytes>=1900);
});

test('R2544.25 residual memory bounds verbose lifetime aggregates while preserving measured totals',()=>{
  const input=body();input.state.experienceMemory.lifetime={samples:177,netPnl:-170.9,detail:'L'.repeat(2600)};input.state.experienceMemory.tradeLessons.lifetime={samples:177,net:-170.9,detail:'T'.repeat(1400)};
  const out=J.prepareDecisionRequest(input);assert.equal(out.ok,true,JSON.stringify(out.diagnostics));assert.ok(out.diagnostics.bytes<=46000,`bytes=${out.diagnostics.bytes}`);assert.equal(out.body.state.experienceMemory.lifetime.samples,177);assert.equal(out.body.state.experienceMemory.lifetime.netPnl,-170.9);assert.ok(out.diagnostics.sections.experienceMemory<=3200,`memory=${out.diagnostics.sections.experienceMemory}`);assert.ok(out.diagnostics.trimStepsApplied.includes('PASS2_RESIDUAL_MEMORY_TIGHT'));
});
